# Concepts for transport data
#
# Each concept has an:
# - _id: short, machine readable.
# - _name: short, human readable. If not given, this defaults to the ID,
#    title-cased.
# - _description: long, human readable. Optional.
#
# Concepts may be hierarchical. The top-level concepts can be used as
# dimensions when specifying the template.

type:
  _description: Objects being transported.
  passenger: ~
  freight: ~

mode:
  all:
    _description: All transport modes.
  air:
    _description: Aviation.
  road:
  rail: ~
  water: ~

vehicle:
  _description: Types of vehicles.
  all:
    _description: All vehicle types.
  ldv:
    _name: LDV
    _description: >
      Light-duty road vehicle, including cars, SUVs, and light trucks.
  bus: ~
  truck: ~
  2w+3w:
    _name: '2W+3W'
    _description: Two- and three-wheeled road vehicles.

fuel:
  all:
    _description: All fuels.
  liquid:
    _name: All liquid
    diesel: ~
    gasoline: ~
    biofuel:
      _name: Liquid biofuel
    synthetic:
      _description: a.k.a. synfuels, electrofuels.
  ng:
    _name: Natural gas
  hydrogen: ~
  electricity: ~

technology:
  _description: Energy conversion technology used to power a motorized vehicle.
  all:
    _description: All technologies.
  combustion:
    _description: >
      Using only chemical fuels. Inclusive of powertrains that store energy as
      electricity, i.e. hybrids.
  electric: ~
  hybrid:
    _description: Using both electricity and chemical fuels.
  fc:
    _name: Fuel cell
    _description: Using electrochemical conversion of fuel to electricity.

automation:
  _description: Degree of automation in operation of transport vehicles.
  human:
    _name: Human
    _description: Vehicle operated by a human driver.
  av:
    _name: Automated
    _description: Fully-automated (self-driving) vehicle.

operator:
  own:
    _name: Own-supplied
    _description: >
      Transport by a vehicle owned and operated for private use by a household
      or individual.
  hire:
    _name: Hired
    _description: >
      Transport by a vehicle (and driver) hired through a firm or commercial
      service.

pollutant:
  ghg:
    _name: GHG
    _description: >
      Greenhouse gases.
      Where used for totals, all GHGs are conveted to an equivalence basis.
    co2:
      _name: CO₂
      _description: Carbon dioxide.
  aq:
    _description: Air quality-related pollutant species.
    bc:
      _name: BC
      _description: Black carbon.
    nox:
      _name: NOx
      _description: Air quality-related nitrogen oxides, i.e. NO, NO₂, and N₂O.
    pm25:
      _name: PM2.5
      _description: Particulate matter smaller than 2.5 μm.
    so2:
      _name: SO₂
      _description: Sulfur dioxide.

lca_scope:
  _name: LCA scope
  _description: Scope of analysis covered by a transport life-cycle measure.
  ttw:
    _name: Tank-to-wheels
  wtw:
    _name: Well-to-wheels
  wtt:
    _name: Well-to-tank

fleet:
  _description: Part or all of a collection of transport vehicles.
  new:
    _description: Only newly-sold vehicles in the reporting period.
  used:
    _description: >
      Only used vehicles that were not manufactured in the reporting period.
  all:
    _description: All vehicles in use in the reporting period.
