T000:
  url: https://stats.oecd.org/index.aspx?queryid=79863
  name: "Passenger transport: Inland passenger transport"
  active: true

T001:
  name: Coastal Transport
  fetch:
    type: sdmx
    args:
      source: OECD
      resource_id: ITF_GOODS_TRANSPORT
      key: .T-SEA-CAB
      validate: false
  active: true

T002:
  url: https://stats.oecd.org/Index.aspx?DataSetCode=ITF_GOODS_TRANSPORT
  name: Container Transport
  active: true

T003:
  url: https://stats.oecd.org/Index.aspx?DataSetCode=ITF_GOODS_TRANSPORT#
  name: Inland Freight Transport
  active: true

T004:
  url: https://w3.unece.org/PXWeb2015/pxweb/en/STAT/STAT__40-TRTRANS__03-TRRoadFleet/08_en_TRRoadNewVehF_r.px/?rxid=674effaa-3926-4d2e-9d6d-abfd7dd196b8
  name: New Road Vehicle Registrations by Vehicle Category and Fuel Type
  active: true

T005:
  url: https://datasource.kapsarc.org/explore/dataset/passenger-road-vehicle-fleet-and-rate-per-thousand-inhabitants-by-vehicle-catego/information/?disjunctive.country_name&disjunctive.date&disjunctive.frequency&disjunctive.measurement_name&disjunctive.vehicle_category_name
  name: Passenger Road Vehicle Fleet and rate per thousand inhabitants by Vehicle Category

T006:
  url: https://datasource.kapsarc.org/explore/dataset/passenger-transport/information/?disjunctive.country_name&disjunctive.date&disjunctive.frequency&disjunctive.variable_name
  name: Passenger Transport

T007:
  url: https://datasource.kapsarc.org/explore/dataset/new-passenger-car-registrations-by-fuel-type/information/?disjunctive.country_name&disjunctive.date&disjunctive.frequency&disjunctive.fuel_type_name
  name: New Passenger Car Registrations by Fuel type

T008:
  url: https://datasource.kapsarc.org/explore/dataset/new-road-vehicle-registrations-by-vehicle-category-and-fuel-type/information/?disjunctive.country_name&disjunctive.date&disjunctive.frequency&disjunctive.fuel_type_name&disjunctive.type_of_vehicle_name
  name: New Road Vehicle Registrations by Vehicle Category and Fuel type

T009:
  url: https://datasource.kapsarc.org/explore/dataset/road-vehicle-fleet-by-vehicle-category-and-fuel-type/information/?disjunctive.country_name&disjunctive.date&disjunctive.frequency&disjunctive.fuel_type_name&disjunctive.type_of_vehicle_name
  name: Road Vehicle Fleet by Vehicle Category and Fuel Type

T010:
  url: https://datasource.kapsarc.org/explore/dataset/volume-of-passenger-transport-relative-to-gdp/information/?disjunctive.date&disjunctive.frequency&disjunctive.geo_name&disjunctive.measure_name
  name: Volume of passenger transport relative to GDP

T011:
  url: https://datasource.kapsarc.org/explore/dataset/modal-split-of-freight-transport/information/?disjunctive.date&disjunctive.frequency&disjunctive.geo_name&disjunctive.measure_name&disjunctive.tra_mode_name
  name: Modal split of freight transport

T012:
  url: https://datasource.kapsarc.org/explore/dataset/modal-split-of-freight-transport/information/?disjunctive.date&disjunctive.frequency&disjunctive.geo_name&disjunctive.measure_name&disjunctive.tra_mode_name
  name: Modal split of passenger transport

T013:
  url: https://datasource.kapsarc.org/explore/dataset/rail-transport-of-passengers/information/?disjunctive.date&disjunctive.frequency&disjunctive.geo_name&disjunctive.measure_name&disjunctive.tra_cov_name
  name: Rail transport of passengers

T014:
  url: https://datasource.kapsarc.org/explore/dataset/supply-transformation-and-consumption-of-electricity-annual-data/information/?disjunctive.date&disjunctive.frequency&disjunctive.geo_name&disjunctive.indic_nrg_name&disjunctive.measure_name&disjunctive.product_name&dataChart=eyJxdWVyaWVzIjpbeyJjb25maWciOnsiZGF0YXNldCI6InN1cHBseS10cmFuc2Zvcm1hdGlvbi1hbmQtY29uc3VtcHRpb24tb2YtZWxlY3RyaWNpdHktYW5udWFsLWRhdGEiLCJvcHRpb25zIjp7ImRpc2p1bmN0aXZlLmRhdGUiOnRydWUsImRpc2p1bmN0aXZlLmZyZXF1ZW5jeSI6dHJ1ZSwiZGlzanVuY3RpdmUuZ2VvX25hbWUiOnRydWUsImRpc2p1bmN0aXZlLmluZGljX25yZ19uYW1lIjp0cnVlLCJkaXNqdW5jdGl2ZS5tZWFzdXJlX25hbWUiOnRydWUsImRpc2p1bmN0aXZlLnByb2R1Y3RfbmFtZSI6dHJ1ZX19LCJjaGFydHMiOlt7ImFsaWduTW9udGgiOnRydWUsInR5cGUiOiJsaW5lIiwiZnVuYyI6IkFWRyIsInlBeGlzIjoidmFsdWUiLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZSwiY29sb3IiOiIjNjZjMmE1In1dLCJ4QXhpcyI6ImRhdGUiLCJtYXhwb2ludHMiOiIiLCJ0aW1lc2NhbGUiOiJ5ZWFyIiwic29ydCI6IiJ9XSwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZX0%3D
  name: Supply, transformation and consumption of electricity

T015:
  url: https://datasource.kapsarc.org/explore/dataset/supply-transformation-and-consumption-of-gas-annual-data/information/?disjunctive.date&disjunctive.frequency&disjunctive.geo_name&disjunctive.indic_nrg_name&disjunctive.measure_name&disjunctive.product_name
  name: Supply, transformation and consumption of gas

T016:
  url: https://datasource.kapsarc.org/explore/dataset/supply-transformation-and-consumption-of-oil-annual-data/information/?disjunctive.date&disjunctive.frequency&disjunctive.geo_name&disjunctive.indic_nrg_name&disjunctive.measure_name&disjunctive.product_name
  name: Supply, transformation and consumption of oil

T017:
  url: https://datasource.kapsarc.org/explore/dataset/simplified-energy-balances-annual-data/information/?disjunctive.date&disjunctive.geo_name&disjunctive.indic_nrg_name&disjunctive.measure_name&disjunctive.product_name
  name: N/A

T018:
  url: https://datasource.kapsarc.org/explore/dataset/transport-infrastructure-investment-and-maintenance-spending/information/?disjunctive.country_name&disjunctive.date&disjunctive.frequency&disjunctive.measure_name&disjunctive.variable_name
  name: Transport infrastructure investment and maintenance spending

T019:
  url: https://datasource.kapsarc.org/explore/dataset/electricity-consumption-by-industry-transport-activities-and-householdsservices-/information/?disjunctive.date&disjunctive.frequency&disjunctive.geo_name&disjunctive.indic_nrg_name&disjunctive.measure_name&disjunctive.product_name
  name: Electricity consumption by industry, transport activities and households/services

T020:
  url: https://datasource.kapsarc.org/explore/dataset/final-energy-consumption-by-product/information/?disjunctive.date&disjunctive.frequency&disjunctive.geo_name&disjunctive.measure_name
  name: Final energy consumption by product

T021:
  url: https://datasource.kapsarc.org/explore/dataset/goods-transport-by-rail/information/?disjunctive.date&disjunctive.frequency&disjunctive.geo_name&disjunctive.measure_name&disjunctive.tra_cov_name
  name: Goods transport by rail

T022:
  url: https://datasource.kapsarc.org/explore/dataset/new-goods-road-vehicles-registered-by-vehicle-category-and-permissible-maximum-g/information/?disjunctive.country_name&disjunctive.date&disjunctive.frequency&disjunctive.vehicle_category_name
  name: New Goods Road Vehicles Registered by Vehicle Category and Permissible Maximum Gross weight group

T023:
  url: https://datasource.kapsarc.org/explore/dataset/goods-road-vehicle-fleet-by-vehicle-category-and-permissible-maximum-gross-weigh/information/?disjunctive.country_name&disjunctive.date&disjunctive.frequency&disjunctive.vehicle_category_name
  name: Goods Road Vehicle Fleet by Vehicle Category and Permissible Maximum Gross weight group

T024:
  url: https://datasource.kapsarc.org/explore/dataset/supply-transformation-and-consumption-of-renewable-energies-annual-data/information/?disjunctive.date&disjunctive.frequency
  name: Supply, transformation and consumption of renewable energies

T025:
  url: https://edgar.jrc.ec.europa.eu/overview.php?v=50_GHG
  name: EDGAR v5.0 Global Greenhouse Gas Emissions
  description: |
    7.1 Direct CO2 emissions from global (and regional) transport scenarios.
    7.2 Transport demand/activity trajectories for passenger and freight.
    7.3 Mode shares of passenger and freight transport
    7.4 Energy intensity of freight and passenger transport
    7.5 Fuel shares (freight and passenger transport)
